// <auto-generated />
namespace Techspiders.Pos.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Categoriestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Categoriestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201812240720033_Categoriestable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
